#!/bin/sh 
# 刷新图标缓存
gtk-update-icon-cache /usr/share/icons/bloom
# 向服务器返回安装数加1（不显示内容且忽略错误）
curl http://120.25.153.144/spark-simple-remote-desktop-accessor/Install.php?Version=1.2.0-1 -s > /dev/null | true
